import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [{ type: 'autogenerated', dirName: 'documentation' }],
  exercisesSidebar: [{ type: 'autogenerated', dirName: 'exercises' }],
  examExercisesSidebar: [{ type: 'autogenerated', dirName: 'exam-exercises' }],
  additionalMaterialSidebar: [
    { type: 'autogenerated', dirName: 'additional-material' },
  ],
};

export default sidebars;
