name: Pull Request Checks

on:
  pull_request:

jobs:
  ci:
    name: verify buildable state
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: check formatting
        run: npm run prettier:check

      - name: check mdx format for docusaurus v3 compatibility
        run: npx docusaurus-mdx-checker

      - name: build website
        run: npm run build
